In [1]:
import librosa
import librosa.display
import matplotlib.pyplot as plt

In [41]:
# DEPRECATED
# Load the Drive helper and mount
#from google.colab import drive
#
# This will prompt for authorization.
#drive.mount('/content/drive')

In [50]:
RECORDINGS_PATH = "/Users/ntuan1/workspaces/content/drive/MyDrive/amd-training"
PICKLE_FILE_NAME  = "df-40-200-mfccs-kaiser_fast-01-25-19"

In [51]:
#compute
import glob, os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import uuid

os.chdir(RECORDINGS_PATH)
df = pd.DataFrame(columns=['file_path', 'mfccs_40', 'chroma', 'mel','contrast','tonnetz', 'duration','label'])
df = df.fillna(0) # with 0s rather than NaNs
def process(file, label):
  try:
    print("processing {}".format(file))
    
    # here kaiser_fast is a technique used for faster extraction
    X, sample_rate = librosa.load(file, sr=16000,res_type='kaiser_fast')
    duration = librosa.get_duration(y=X, sr=sample_rate)
    stft = np.abs(librosa.stft(X))
    mfccs_40 = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=40).T,axis=0)
    chroma = np.mean(librosa.feature.chroma_stft(S=stft, sr=sample_rate).T,axis=0)
    
    S = librosa.feature.melspectrogram(y=X, sr=sample_rate, n_mels=128,fmax=8000)
    print(S.T)
    mel = np.mean(S.T,axis=0)
    contrast = np.mean(librosa.feature.spectral_contrast(S=stft, sr=sample_rate).T,axis=0)
    tonnetz = np.mean(librosa.feature.tonnetz(y=librosa.effects.harmonic(X),
    sr=sample_rate).T,axis=0)

    row = pd.Series({'file_path':file,'mfccs_40':mfccs_40, 'chroma':chroma, 'mel':mel, 'contrast':contrast, 'tonnetz':tonnetz, 'duration':duration,'label':label},name=7)
    df.loc[len(df)] = row  
    
  except Exception as e:
    print("Error encountered while parsing file: {} by {}".format(file, e))


def download_files(path, label, max=100):
  index = 0
  for file in glob.glob(path):
    print("{} file in folder".format(file))
    if index <=max:
      row = process(file, label)
      df.loc[len(df)] = row
      index = index +1

#save the df for reusabality
df.to_pickle(PICKLE_FILE_NAME+".pkl")
print(df.to_json())


{"file_path":{},"mfccs_40":{},"chroma":{},"mel":{},"contrast":{},"tonnetz":{},"duration":{},"label":{}}


In [53]:
#%debug
# df = pd.DataFrame(columns=['file_path', 'mfccs_40', 'chroma', 'mel','contrast','tonnetz', 'duration','label'])
# df = df.fillna(0) # with 0s rather than NaNs

#os.chdir(RECORDINGS_PATH)
download_files("answering-machine/*.wav", label="beep")
download_files("careangel-recordings/*.wav", label="beep")
download_files("speech/*.wav", label="speech")


answering-machine/beep-02.wav file in folder
processing answering-machine/beep-02.wav
[[4.86097193e+00 4.81086588e+00 4.23651171e+00 ... 6.50803733e-04
  1.73715409e-04 7.74035725e-05]
 [1.22374141e+00 1.22051919e+00 1.15765774e+00 ... 9.43869236e-04
  1.53644578e-04 2.52305599e-05]
 [5.27865067e-03 1.00434329e-02 1.13752440e-01 ... 9.17277590e-04
  1.34250498e-04 8.71309385e-06]
 ...
 [9.31038463e-04 1.63385645e-03 1.33670926e-01 ... 9.17079684e-04
  1.30478977e-04 7.67949041e-06]
 [7.86661077e-03 1.87538173e-02 1.01720326e-01 ... 8.74675869e-04
  1.28153755e-04 9.74775594e-06]
 [6.87003462e-03 2.39420235e-02 1.63774058e-01 ... 6.64635387e-04
  9.85512743e-05 9.24664346e-06]]
answering-machine/beep-01.wav file in folder
processing answering-machine/beep-01.wav
[[2.5705576e-01 2.5656611e-01 2.6012164e-01 ... 2.6235028e-05
  1.7473574e-05 1.7122795e-05]
 [6.4479880e-02 6.3859709e-02 6.5308385e-02 ... 2.5442012e-05
  4.4885073e-06 4.2452434e-06]
 [7.4975296e-06 8.2413217e-06 6.3090042e-0

/Users/ntuan1/.local/share/virtualenvs/ToolSetAndTips-QIdSQBWd/lib/python3.9/site-packages/librosa/core/spectrum.py:257: UserWarning: n_fft=512 is too large for input signal of length=305
  warnings.warn(
/Users/ntuan1/.local/share/virtualenvs/ToolSetAndTips-QIdSQBWd/lib/python3.9/site-packages/librosa/core/spectrum.py:257: UserWarning: n_fft=512 is too large for input signal of length=153
  warnings.warn(
/Users/ntuan1/.local/share/virtualenvs/ToolSetAndTips-QIdSQBWd/lib/python3.9/site-packages/librosa/core/spectrum.py:257: UserWarning: n_fft=512 is too large for input signal of length=77
  warnings.warn(
/Users/ntuan1/.local/share/virtualenvs/ToolSetAndTips-QIdSQBWd/lib/python3.9/site-packages/librosa/core/spectrum.py:257: UserWarning: n_fft=512 is too large for input signal of length=358
  warnings.warn(
/Users/ntuan1/.local/share/virtualenvs/ToolSetAndTips-QIdSQBWd/lib/python3.9/site-packages/librosa/core/spectrum.py:257: UserWarning: n_fft=512 is too large for input signal of leng

answering-machine/beep-04.wav file in folder
processing answering-machine/beep-04.wav
[[3.5955384e-02 3.5909519e-02 3.5897642e-02 ... 6.7661080e-04
  5.2499276e-04 4.5771911e-04]
 [8.9814104e-03 8.9668464e-03 9.0021957e-03 ... 1.6850907e-04
  1.2968818e-04 1.1472735e-04]
 [2.6109351e-06 2.4760154e-06 1.5291273e-06 ... 8.1656867e-07
  1.7078561e-07 1.9699912e-06]
 ...
 [1.0313536e-06 2.8000807e-06 2.0375519e-06 ... 7.5638104e-07
  1.6525125e-07 2.1166452e-06]
 [4.7839280e-06 8.3807208e-06 3.1225941e-06 ... 8.9078083e-07
  1.4966270e-07 2.3323787e-06]
 [4.3868467e-06 1.2330318e-05 5.0574781e-06 ... 9.7448890e-07
  4.1486743e-07 1.7433206e-06]]
answering-machine/beep-06.wav file in folder
processing answering-machine/beep-06.wav
[[1.7034529e+01 1.7000387e+00 6.9835174e-01 ... 1.0413951e-03
  3.7607021e-04 1.2059419e-04]
 [1.7962814e+01 4.3976933e-01 1.8187083e-01 ... 2.6249225e-04
  9.4932169e-05 3.1865053e-05]
 [1.4029603e+01 1.5965887e-05 1.6292815e-05 ... 6.2898680e-06
  1.0401853e-06 

/Users/ntuan1/.local/share/virtualenvs/ToolSetAndTips-QIdSQBWd/lib/python3.9/site-packages/librosa/core/spectrum.py:257: UserWarning: n_fft=512 is too large for input signal of length=299
  warnings.warn(
/Users/ntuan1/.local/share/virtualenvs/ToolSetAndTips-QIdSQBWd/lib/python3.9/site-packages/librosa/core/spectrum.py:257: UserWarning: n_fft=512 is too large for input signal of length=150
  warnings.warn(
/Users/ntuan1/.local/share/virtualenvs/ToolSetAndTips-QIdSQBWd/lib/python3.9/site-packages/librosa/core/spectrum.py:257: UserWarning: n_fft=512 is too large for input signal of length=265
  warnings.warn(
/Users/ntuan1/.local/share/virtualenvs/ToolSetAndTips-QIdSQBWd/lib/python3.9/site-packages/librosa/core/spectrum.py:257: UserWarning: n_fft=512 is too large for input signal of length=133
  warnings.warn(
/Users/ntuan1/.local/share/virtualenvs/ToolSetAndTips-QIdSQBWd/lib/python3.9/site-packages/librosa/core/spectrum.py:257: UserWarning: n_fft=512 is too large for input signal of len

answering-machine/beep-09.wav file in folder
processing answering-machine/beep-09.wav
[[1.4635324e-01 1.4518639e-01 1.4825292e-01 ... 1.0885559e-04
  8.4686100e-05 7.2192168e-05]
 [3.6600936e-02 3.5976555e-02 3.7595149e-02 ... 2.7121288e-05
  2.1128160e-05 1.9021960e-05]
 [1.0132778e-05 6.1215047e-05 3.3285408e-04 ... 2.6107327e-07
  1.7507290e-07 1.3183727e-06]
 ...
 [2.2349403e-05 5.5720619e-05 3.9536972e-04 ... 2.3636548e-07
  1.6457294e-07 1.4395505e-06]
 [1.8640929e-05 7.3128351e-05 4.5882509e-04 ... 3.1931677e-07
  2.0232073e-07 1.4431012e-06]
 [8.1002421e-05 1.4250600e-04 3.2135862e-04 ... 1.3949899e-06
  8.9442432e-07 1.5744538e-06]]
answering-machine/beep-08b.wav file in folder
processing answering-machine/beep-08b.wav
[[6.94587454e-02 7.06926584e-02 7.30937347e-02 8.43995959e-02
  6.10476397e-02 5.59878498e-02 6.21063784e-02 6.45846725e-02
  6.55302778e-02 6.51441514e-02 6.76001757e-02 6.81829751e-02
  6.58554360e-02 6.87884092e-02 7.02612996e-02 7.02215359e-02
  7.19150007e-

/Users/ntuan1/.local/share/virtualenvs/ToolSetAndTips-QIdSQBWd/lib/python3.9/site-packages/librosa/core/spectrum.py:257: UserWarning: n_fft=512 is too large for input signal of length=358
  warnings.warn(
/Users/ntuan1/.local/share/virtualenvs/ToolSetAndTips-QIdSQBWd/lib/python3.9/site-packages/librosa/core/spectrum.py:257: UserWarning: n_fft=512 is too large for input signal of length=179
  warnings.warn(
/Users/ntuan1/.local/share/virtualenvs/ToolSetAndTips-QIdSQBWd/lib/python3.9/site-packages/librosa/core/spectrum.py:257: UserWarning: n_fft=512 is too large for input signal of length=271
  warnings.warn(
/Users/ntuan1/.local/share/virtualenvs/ToolSetAndTips-QIdSQBWd/lib/python3.9/site-packages/librosa/core/spectrum.py:257: UserWarning: n_fft=512 is too large for input signal of length=136
  warnings.warn(
/Users/ntuan1/.local/share/virtualenvs/ToolSetAndTips-QIdSQBWd/lib/python3.9/site-packages/librosa/core/spectrum.py:257: UserWarning: n_fft=512 is too large for input signal of len

speech/134218211_100662903@10.9.6.4.wav file in folder
processing speech/134218211_100662903@10.9.6.4.wav
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 ...
 [2.2335760e-06 4.8671686e-06 7.2333296e-06 ... 2.4818489e-16
  3.1996132e-16 3.0644916e-16]
 [1.4768987e-06 9.5339074e-06 5.6129456e-06 ... 2.4759719e-12
  2.4040197e-12 2.3580907e-12]
 [1.4154001e-06 3.3083120e-06 2.3135792e-06 ... 1.5059573e-11
  1.4621544e-11 1.4341964e-11]]
speech/134742501_125768259@10.9.6.4.wav file in folder
processing speech/134742501_125768259@10.9.6.4.wav
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
speech/134219003_125742931@10.9.6.4.wav file in folder
processing sp

In [54]:
df.dropna(inplace=True)

In [55]:
df.label.value_counts()

label
beep      16
speech    15
Name: count, dtype: int64

In [56]:
df.to_pickle("amd-df-01-29-10-41"+".pkl")

In [57]:
df1 = pd.read_pickle("amd-df-01-29-10-41.pkl")


In [58]:
df1

file_path  \
0                       answering-machine/beep-02.wav   
2                       answering-machine/beep-01.wav   
4                      answering-machine/beep-07a.wav   
6                       answering-machine/beep-04.wav   
8                       answering-machine/beep-06.wav   
10  answering-machine/75ea624b-8ab9-4e17-9000-70e9...   
12                      answering-machine/beep-09.wav   
14                     answering-machine/beep-08b.wav   
16    speech/5c082690-02f2-11e9-aa3d-ad1a095d8d72.wav   
18            speech/134218211_100662903@10.9.6.4.wav   
20            speech/134742501_125768259@10.9.6.4.wav   
22            speech/134219003_125742931@10.9.6.4.wav   
24            speech/134218701_124515005@10.9.6.4.wav   
26    speech/26b25bb7-6825-43e7-b8bd-03a3884ed694.wav   
28            speech/134480846_117308603@10.9.6.4.wav   
30  speech-recordings/134742511_100538577@10.9.6.4...   
32                      answering-machine/beep-02.wav   
34                      answering-machine/beep-01.wav   
36                     answering-machine/beep-07a.wav   
38                      answering-machine/beep-04.wav   
40                      answering-machine/beep-06.wav   
42  answering-machine/75ea624b-8ab9-4e17-9000-70e9...   
44                      answering-machine/beep-09.wav   
46                     answering-machine/beep-08b.wav   
48    speech/5c082690-02f2-11e9-aa3d-ad1a095d8d72.wav   
50            speech/134218211_100662903@10.9.6.4.wav   
52            speech/134742501_125768259@10.9.6.4.wav   
54            speech/134219003_125742931@10.9.6.4.wav   
56            speech/134218701_124515005@10.9.6.4.wav   
58    speech/26b25bb7-6825-43e7-b8bd-03a3884ed694.wav   
60            speech/134480846_117308603@10.9.6.4.wav   

                                             mfccs_40  \
0   [-97.78767, 1.9121733, 8.148039, 23.516476, -1...   
2   [-392.9721, 11.7795515, -23.080708, -50.315006...   
4   [-235.76114, 40.16065, -103.155655, 6.074047, ...   
6   [-435.2159, -18.246925, -19.837187, 28.130121,...   
8   [-300.8038, -41.312534, 10.463231, 29.02023, 6...   
10  [-447.4011, 55.21608, -27.44261, 7.5541935, -3...   
12  [-400.04636, -0.34393036, -31.725119, -26.0384...   
14  [-293.19034, 4.2567058, -70.523796, 18.705969,...   
16  [-369.00995, 167.48482, -23.750975, 46.112827,...   
18  [-553.1646, 56.906208, -14.359418, 4.9091873, ...   
20  [-396.50217, 130.34111, -30.544592, 20.79164, ...   
22  [-466.47168, 95.85185, -39.552246, 6.730136, 3...   
24  [-414.9159, 130.40039, -52.09449, 5.63395, -4....   
26  [-315.57935, 138.88734, -52.6094, 29.542448, -...   
28  [-473.82718, 97.91772, -30.986328, 10.655597, ...   
30  [-528.82916, 49.89834, 6.778003, 7.3712664, -1...   
32  [-97.78767, 1.9121733, 8.148039, 23.516476, -1...   
34  [-392.9721, 11.7795515, -23.080708, -50.315006...   
36  [-235.76114, 40.16065, -103.155655, 6.074047, ...   
38  [-435.2159, -18.246925, -19.837187, 28.130121,...   
40  [-300.8038, -41.312534, 10.463231, 29.02023, 6...   
42  [-447.4011, 55.21608, -27.44261, 7.5541935, -3...   
44  [-400.04636, -0.34393036, -31.725119, -26.0384...   
46  [-293.19034, 4.2567058, -70.523796, 18.705969,...   
48  [-369.00995, 167.48482, -23.750975, 46.112827,...   
50  [-553.1646, 56.906208, -14.359418, 4.9091873, ...   
52  [-396.50217, 130.34111, -30.544592, 20.79164, ...   
54  [-466.47168, 95.85185, -39.552246, 6.730136, 3...   
56  [-414.9159, 130.40039, -52.09449, 5.63395, -4....   
58  [-315.57935, 138.88734, -52.6094, 29.542448, -...   
60  [-473.82718, 97.91772, -30.986328, 10.655597, ...   

                                               chroma  \
0   [0.15613975, 0.12301526, 0.25473025, 0.1193895...   
2   [0.17693055, 0.013545142, 0.013969152, 0.02721...   
4   [0.050724536, 0.042279888, 0.039348125, 0.0486...   
6   [0.008847945, 0.009358507, 0.014058292, 0.1542...   
8   [0.028244575, 0.031693, 0.039061435, 0.1646129...   
10  [0.016357066, 0.024264337, 0.19517124, 1.0, 0...